# =================================
# SERVICE CONFIGURATION
# =================================
spring:
  application:
    name: gescom-eureka-discovery-service
  config:
    import: optional:configserver:http://localhost:8888
  profiles:
    active: prod
